site_name: real_option_models_rl
site_description: Application of Reainforcement Learning in solving optimal stopping problems for real options.

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep purple
      accent: purple

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple
      accent: purple
  features:
    - navigation.tabs

plugins:
  - search
  - mkdocs-jupyter:
      include_source: true
      execute: false


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - attr_list

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home Page: README.md
  - Theoretical Introduction: Theory.md
  - Algorithms and Simulations:
    - Algorithm 1: notebooks/01_algorithm_1_pi_pi_os.ipynb
    - Algorithm 4: notebooks/02_algorithm_4_spi_pi_os.ipynb
  - Results Gallery: gallery.md

extra_css:
  - stylesheets/extra.css